[book]
authors = ["Faan Tone Liu"]
language = "en"
multilingual = false
src = "src"
title = "Introduction to Programming 2"

[build]
build-dir = "docs"

[output.html]
default-theme = "rust"
additional-js = ["js/disable_keyboard.js"]
additional-css = ["css/pyscript.css"]
no-section-label = true

[output.html.playground]
editable = true
