name: Build, Commit, and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install and run mdbook to build the documentation
      - name: Install mdBook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz | tar xvz
          sudo mv mdbook /usr/local/bin/
        
      - name: Build Documentation
        run: mdbook build

      # Commit the built files back to the repository
      - name: Commit and Push Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add built documentation" || exit 0  # exit 0 if no files to commit
          git push

      # Setup SSH Key
      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          eval $(ssh-agent -s)
          ssh-add deploy_key

      # Deploy the built documentation to the remote server using rsync
      - name: Deploy Documentation to Remote Server
        run: rsync -ravP --rsh "ssh -o StrictHostKeyChecking=no -v" docs/* intropython@linux.cs.du.edu:~/public_html/intro-to-programming